export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_CITIES_START = "FETCH_CITIES_START";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_FAIL = "FETCH_CITIES_FAIL";

export const POST_CITY_START = "POST_CITY_START";
export const POST_CITY_SUCCESS = "POST_CITY_SUCCESS";
export const POST_CITY_FAIL = "POST_CITY_FAIL";

export const SAVE_NEW_CITY = "SAVE_NEW_CITY";
export const UPDATE_CITY = "UPDATE_CITY";
export const UPDATE_CITY_SUCCESS = "UPDATE_CITY_SUCCESS";
export const DELETE_CITY = "DELETE_CITY";
export const DELETE_CITY_SUCCESS = "DELETE_CITY_SUCCESS";

export const FETCH_TRANSITS = "FETCH_TRANSITS";
export const FETCH_TRANSITS_START = "FETCH_TRANSITS_START";
export const FETCH_TRANSITS_SUCCESS = "FETCH_TRANSITS_SUCCESS";
export const SAVE_NEW_TRANSIT = "SAVE_NEW_TRANSIT";
export const UPDATE_TRANSIT = "UPDATE_TRANSIT";
export const UPDATE_TRANSIT_SUCCESS = "UPDATE_TRANSIT_SUCCESS";
export const DELETE_TRANSIT = "DELETE_TRANSIT";
export const DELETE_TRANSIT_SUCCESS = "DELETE_TRANSIT_SUCCESS";


//export const SAVE_NEW_INPUT_DATA = "SAVE_NEW_INPUT_DATA";

export const FETCH_SPENTS = "FETCH_SPENTS";
export const FETCH_SPENTS_SUCCESS = "FETCH_SPENTS_SUCCESS";
export const ADD_NEW_SPENT = "ADD_NEW_SPENT";
export const ADD_NEW_SPENT_SUCCESS = "ADD_NEW_SPENT_SUCCESS";
export const EDIT_SPENT = "EDIT_SPENT";
export const EDIT_SPENT_SUCCESS = "EDIT_SPENT_SUCCESS";
export const DELETE_SPENT = "DELETE_SPENT";
export const DELETE_SPENT_SUCCESS = "DELETE_SPENT_SUCCESS";


export const FETCH_NOTES = "FETCH_NOTES";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const ADD_NEW_NOTE = "ADD_NEW_NOTE";
export const EDIT_NOTE = "EDIT_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";

export const FETCH_TICKETS = "FETCH_TICKETS";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const ADD_NEW_TICKET = "ADD_NEW_TICKET";
export const EDIT_TICKET = "EDIT_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";

export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_COMPLETED_TODOS = "FETCH_COMPLETED_TODOS";
export const FETCH_COMPLETED_TODOS_SUCCESS = "FETCH_COMPLETED_TODOS_SUCCESS";
export const ADD_NEW_TODO = "ADD_NEW_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_ALL_TODOS = "DELETE_ALL_TODOS";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_COMPLETED_TODO = "DELETE_COMPLETED_TODO";
export const MARK_TODO_COMPLETED ="MARK_TODO_COMPLETED";
export const MARK_TODO_NOT_COMPLETED ="MARK_TODO_NOT_COMPLETED";

export const FETCH_PACKS = "FETCH_PACKS";
export const FETCH_PACKS_SUCCESS = "FETCH_PACKS_SUCCESS";
export const FETCH_PACKEDS = "FETCH_PACKEDS";
export const FETCH_PACKEDS_SUCCESS = "FETCH_PACKEDS_SUCCESS";
export const ADD_NEW_PACK = "ADD_NEW_PACK";
export const EDIT_PACK = "EDIT_PACK";
export const DELETE_ALL_PACKEDS = "DELETE_ALL_PACKEDS";
export const DELETE_PACK = "DELETE_PACK";
export const DELETE_PACKED = "DELETE_PACKED";
export const MARK_PACKED ="MARK_PACKED";
export const MARK_NOT_PACKED ="MARK_NOT_PACKED";

